[package]
name = "sketch"
description = "Sketch feature: bezier curves drawn on a plane"

repository.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
bevy = { version = "0.18.0", default-features = false, features = ["3d", "file_watcher"] }
bezier = { path = "../bezier" }
command-system = { path = "../commands" }
